import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import '../assets/sass/global.scss';

export const metadata: Metadata = {
  title: "VibrLink | Fanlink generator",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <link rel="icon" type="image/ico" href="/vibrlink-favicon.ico" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
